export enum RoleTypes {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_MANAGER = 'ROLE_MANAGER',
  ROLE_USER = 'ROLE_USER',
  ROLE_TIER_0 = 'ROLE_TIER_0',
  ROLE_TIER_1 = 'ROLE_TIER_1',
  ROLE_TIER_2 = 'ROLE_TIER_2'
}
